<?php
/**
 * ImportCertReq
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ISECure WS Channel API
 *
 * The API provides normal file based access to all common banks in Finland via WebServices channel on the service side, including certificate enrollment (PKI) with automatic renewals. Additionally, user account management, password recovery, and SMS based 2nd or Multi Factor Authentication (MFA) are provided (AWS Cognito Your User Pool). Access is secured with HTTPS/TLS (AWS API Gateway), using email address as username and password. On login, password is RSA encrypted along with dynamic parameters fetched from the service (username specific challenge response). Every integrator has own API Key and every user account belongs to one integrator. Certificate sharing between accounts is possible under the same integrator API Key, meaning that the enrolled bank connection certificates are shared. Under the same email address / username, both *admin* and *data* accounts must be used as they have separate passwords and differing functions.
 *
 * OpenAPI spec version: v2.3.0
 * Contact: dan.forsberg@isecure.fi
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * ImportCertReq Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ImportCertReq implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ImportCertReq';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'certificate' => 'string',
        'company' => 'string',
        'enc_certificate' => 'string',
        'enc_privatekey' => 'string',
        'private_key' => 'string',
        'ws_target_id' => 'string',
        'ws_user_id' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'certificate' => 'Certificate',
        'company' => 'Company',
        'enc_certificate' => 'EncCertificate',
        'enc_privatekey' => 'EncPrivatekey',
        'private_key' => 'PrivateKey',
        'ws_target_id' => 'WsTargetId',
        'ws_user_id' => 'WsUserId'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'certificate' => 'setCertificate',
        'company' => 'setCompany',
        'enc_certificate' => 'setEncCertificate',
        'enc_privatekey' => 'setEncPrivatekey',
        'private_key' => 'setPrivateKey',
        'ws_target_id' => 'setWsTargetId',
        'ws_user_id' => 'setWsUserId'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'certificate' => 'getCertificate',
        'company' => 'getCompany',
        'enc_certificate' => 'getEncCertificate',
        'enc_privatekey' => 'getEncPrivatekey',
        'private_key' => 'getPrivateKey',
        'ws_target_id' => 'getWsTargetId',
        'ws_user_id' => 'getWsUserId'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['certificate'] = isset($data['certificate']) ? $data['certificate'] : null;
        $this->container['company'] = isset($data['company']) ? $data['company'] : null;
        $this->container['enc_certificate'] = isset($data['enc_certificate']) ? $data['enc_certificate'] : null;
        $this->container['enc_privatekey'] = isset($data['enc_privatekey']) ? $data['enc_privatekey'] : null;
        $this->container['private_key'] = isset($data['private_key']) ? $data['private_key'] : null;
        $this->container['ws_target_id'] = isset($data['ws_target_id']) ? $data['ws_target_id'] : null;
        $this->container['ws_user_id'] = isset($data['ws_user_id']) ? $data['ws_user_id'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['certificate'] === null) {
            $invalid_properties[] = "'certificate' can't be null";
        }
        if ($this->container['company'] === null) {
            $invalid_properties[] = "'company' can't be null";
        }
        if ($this->container['private_key'] === null) {
            $invalid_properties[] = "'private_key' can't be null";
        }
        if ($this->container['ws_target_id'] === null) {
            $invalid_properties[] = "'ws_target_id' can't be null";
        }
        if ($this->container['ws_user_id'] === null) {
            $invalid_properties[] = "'ws_user_id' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['certificate'] === null) {
            return false;
        }
        if ($this->container['company'] === null) {
            return false;
        }
        if ($this->container['private_key'] === null) {
            return false;
        }
        if ($this->container['ws_target_id'] === null) {
            return false;
        }
        if ($this->container['ws_user_id'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets certificate
     * @return string
     */
    public function getCertificate()
    {
        return $this->container['certificate'];
    }

    /**
     * Sets certificate
     * @param string $certificate Certificate in PEM format
     * @return $this
     */
    public function setCertificate($certificate)
    {
        $this->container['certificate'] = $certificate;

        return $this;
    }

    /**
     * Gets company
     * @return string
     */
    public function getCompany()
    {
        return $this->container['company'];
    }

    /**
     * Sets company
     * @param string $company Company name as registered with bank (e.g. full capital letters without Oy, see contract)
     * @return $this
     */
    public function setCompany($company)
    {
        $this->container['company'] = $company;

        return $this;
    }

    /**
     * Gets enc_certificate
     * @return string
     */
    public function getEncCertificate()
    {
        return $this->container['enc_certificate'];
    }

    /**
     * Sets enc_certificate
     * @param string $enc_certificate Certificate in PEM format (encryption certificate for DanskeBank)
     * @return $this
     */
    public function setEncCertificate($enc_certificate)
    {
        $this->container['enc_certificate'] = $enc_certificate;

        return $this;
    }

    /**
     * Gets enc_privatekey
     * @return string
     */
    public function getEncPrivatekey()
    {
        return $this->container['enc_privatekey'];
    }

    /**
     * Sets enc_privatekey
     * @param string $enc_privatekey Private key in PEM format (encryption certificate for DanskeBank)
     * @return $this
     */
    public function setEncPrivatekey($enc_privatekey)
    {
        $this->container['enc_privatekey'] = $enc_privatekey;

        return $this;
    }

    /**
     * Gets private_key
     * @return string
     */
    public function getPrivateKey()
    {
        return $this->container['private_key'];
    }

    /**
     * Sets private_key
     * @param string $private_key Private key in PEM format
     * @return $this
     */
    public function setPrivateKey($private_key)
    {
        $this->container['private_key'] = $private_key;

        return $this;
    }

    /**
     * Gets ws_target_id
     * @return string
     */
    public function getWsTargetId()
    {
        return $this->container['ws_target_id'];
    }

    /**
     * Sets ws_target_id
     * @param string $ws_target_id WebServices channel target id as in contract with bank
     * @return $this
     */
    public function setWsTargetId($ws_target_id)
    {
        $this->container['ws_target_id'] = $ws_target_id;

        return $this;
    }

    /**
     * Gets ws_user_id
     * @return string
     */
    public function getWsUserId()
    {
        return $this->container['ws_user_id'];
    }

    /**
     * Sets ws_user_id
     * @param string $ws_user_id WebServices channel user id as in contract with bank
     * @return $this
     */
    public function setWsUserId($ws_user_id)
    {
        $this->container['ws_user_id'] = $ws_user_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


